name: page_turner_app
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter:
  uses-material-design: true
  assets:
    - assets/images/book.png
    - assets/images/book1.jpg
    - assets/images/book3.jpg
    - assets/images/book4.jpg
    - assets/images/book5.jpg
    - assets/images/book6.jpg
    - assets/images/book7.jpg
    - assets/images/book8.jpg
    - assets/images/book9.jpg 
    - assets/images/book10.jpg 
    - assets/images/book20.jpg
    - assets/images/book11.jpg
    - assets/images/book12.jpg
    - assets/images/book13.jpg
    - assets/images/book14.jpg


  # To add assets to your application, add an assets section, like this:

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700